language: php

php:
  - '7.4'

install:
  - composer install

script:
  - composer test
  - vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
